export const salas = [
  { codigo: '01', descripcion: 'SALA OPERACIONES 01' },
  { codigo: '02', descripcion: 'SALA OPERACIONES 02' },
  { codigo: '03', descripcion: 'SALA DE PARTOS' },
];

export const programacion = [
  {
    codigo: '0000007795',
    diahora: '07:00 a 08:30',
    sala: '01',
    paciente: 'MENDOZA SIERRA , JAQUELINE JOSEFINA',
    intervencion: 'CESAREA',
    cirujano: 'SALVATIERRA ACHA EDUARDO',
    anestesia: 'EPIDURAL',
  },
  {
    codigo: '0000007796',
    diahora: '08:30 a 09:30',
    sala: '02',
    paciente: 'REYES MARQUES , MARIA DEL PILAR',
    intervencion: 'BIOPSIA VULVAR',
    cirujano: 'TANG PLOOG LUIS EDUARDO',
    anestesia: 'GENERAL ENDOVENOSO',
  },
  {
    codigo: '0000007797',
    diahora: '10:00 a 11:30',
    sala: '01',
    paciente: 'TELLO ROURA , CLAUDIA GABRIELA',
    intervencion: 'CESAREA',
    cirujano: 'SALVATIERRA ACHA EDUARDO',
    anestesia: 'EPIDURAL',
  },
  {
    codigo: '0000007798',
    diahora: '12:00 a 13:30',
    sala: '02',
    paciente: 'MORALES REBAZA , GLORIA BETZABETH  EMPERATRIZ',
    intervencion: 'CESAREA',
    cirujano: 'SALVATIERRA ACHA EDUARDO',
    anestesia: 'EPIDURAL',
  },
  {
    codigo: '0000007799',
    diahora: '14:30 a 16:30',
    sala: '01',
    paciente: 'CANTALICIO CRUZ , DIANA MARIA',
    intervencion: 'QUISTECTOMIA LAPARASCOPICA',
    cirujano: 'SALVATIERRA ACHA EDUARDO',
    anestesia: 'GENERAL INHALATORIA',
  },
  {
    codigo: '0000007749',
    diahora: '17:00 a 20:00',
    sala: '01',
    paciente: 'CUYUBAMBA VELIZ , ELIA MAYRA',
    intervencion: 'HISTERECTOMIA LAPARASCOPICA',
    cirujano: 'SALVATIERRA ACHA EDUARDO',
    anestesia: 'GENERAL INHALATORIA',
  },
];

export const anestesia = [
  { codigo: '01', descripcion: 'LOCAL' },
  { codigo: '02', descripcion: 'EPIDURAL' },
  { codigo: '04', descripcion: 'GENERAL ENDOVENOSO' },
  { codigo: '05', descripcion: 'GENERAL INHALATORIA' },
  { codigo: '06', descripcion: 'SEDACION' },
  { codigo: '07', descripcion: 'SIN ANESTESIA' },
  { codigo: '08', descripcion: 'PLEXOBRAQUIAL' },
  { codigo: '15', descripcion: 'SEDACION + LOCAL' },
  { codigo: '16', descripcion: 'EPIDURAL + LOCAL' },
  { codigo: '17', descripcion: 'REGIONAL' },
];

export const intervenciones = [
  {
    codigo: '000001',
    descripcion: 'CESAREA',
    codigoEspecialidad: '005',
    tiempo: 90,
  },
  {
    codigo: '000002',
    descripcion: 'HISTERECTOMIAS CONVENCIONALES MAS BIOPSIA POR CONG',
    codigoEspecialidad: '005',
    tiempo: 180,
  },
  {
    codigo: '000004',
    descripcion: 'HISTERECTOMIA VAGINAL',
    codigoEspecialidad: '005',
    tiempo: 120,
  },
  {
    codigo: '000006',
    descripcion: 'QUISTECTOMIA CONVECIONAL',
    codigoEspecialidad: '005',
    tiempo: 120,
  },
  {
    codigo: '000007',
    descripcion: 'MIOMECTOMIA CONVECIONAL',
    codigoEspecialidad: '005',
    tiempo: 120,
  },
  {
    codigo: '000008',
    descripcion: 'QUISTECTOMIA LAPARASCOPICA',
    codigoEspecialidad: '005',
    tiempo: 120,
  },
  {
    codigo: '000009',
    descripcion: 'MIOMECTOMIA LAPARASCOPICA',
    codigoEspecialidad: '005',
    tiempo: 150,
  },
  {
    codigo: '000010',
    descripcion: 'HISTERECTOMIA LAPARASCOPICA',
    codigoEspecialidad: '005',
    tiempo: 180,
  },
  {
    codigo: '000012',
    descripcion: 'POLIPECTOMIA HISTEROSCOPIA',
    codigoEspecialidad: '005',
    tiempo: 90,
  },
  {
    codigo: '000013',
    descripcion: 'MIOMECTOMIA HISTEROSCOPICA',
    codigoEspecialidad: '005',
    tiempo: 90,
  },
  {
    codigo: '000016',
    descripcion: 'CONOLEEP',
    codigoEspecialidad: '005',
    tiempo: 60,
  },
  {
    codigo: '000018',
    descripcion: 'CERCLAJE',
    codigoEspecialidad: '005',
    tiempo: 30,
  },
  {
    codigo: '000019',
    descripcion: 'MARSUPIALIZACION DE QUISTE DE BARTOLINO',
    codigoEspecialidad: '005',
    tiempo: 30,
  },
  {
    codigo: '000020',
    descripcion: 'CESAREA GEMELAR',
    codigoEspecialidad: '005',
    tiempo: 90,
  },
  {
    codigo: '000003',
    descripcion: 'HISTERECTOMIA CONVENCIONAL',
    codigoEspecialidad: '005',
    tiempo: 120,
  },
  {
    codigo: '000014',
    descripcion: 'CUADRANTECTOMIA Y/O TUMORECTOMIA  DE MAMA',
    codigoEspecialidad: '005',
    tiempo: 90,
  },
  {
    codigo: '000022',
    descripcion: 'BTB',
    codigoEspecialidad: '005',
    tiempo: 90,
  },
  {
    codigo: '000017',
    descripcion: 'LEGRADOS UTERINOS',
    codigoEspecialidad: '005',
    tiempo: 30,
  },
  {
    codigo: '000023',
    descripcion: 'AMEU',
    codigoEspecialidad: '005',
    tiempo: 30,
  },
  {
    codigo: '000015',
    descripcion: 'COLPORRAFIAS',
    codigoEspecialidad: '005',
    tiempo: 120,
  },
  {
    codigo: '000021',
    descripcion: 'COLPORRAFIAS OTROS',
    codigoEspecialidad: '005',
    tiempo: 120,
  },
  {
    codigo: '000025',
    descripcion: 'HISTEROSCOPIA POR SINDROME DE ASHERMAN',
    codigoEspecialidad: '005',
    tiempo: 90,
  },
  {
    codigo: '000026',
    descripcion: 'SALPINGECTOMIA CONVENCIONAL',
    codigoEspecialidad: '005',
    tiempo: 120,
  },
  {
    codigo: '000027',
    descripcion: 'LAPARASCOPIA POR LIBERACION DE ADHERENCIAS',
    codigoEspecialidad: '005',
    tiempo: 120,
  },
  {
    codigo: '000028',
    descripcion: 'BIOPSIA DE ENDOMETRIO',
    codigoEspecialidad: '005',
    tiempo: 30,
  },
  {
    codigo: '000029',
    descripcion: 'DRENAJE DE HEMATOMA VULVAR',
    codigoEspecialidad: '005',
    tiempo: 60,
  },
  {
    codigo: '000011',
    descripcion: 'LAPARASCOPIA QUIRURGICA',
    codigoEspecialidad: '005',
    tiempo: 120,
  },
  {
    codigo: '000030',
    descripcion: 'EXTIRPACION DE PLICOMA VAGINAL',
    codigoEspecialidad: '005',
    tiempo: 60,
  },
  {
    codigo: '000031',
    descripcion: 'SALPINGECTOMIA LAPARASCOPICA',
    codigoEspecialidad: '005',
    tiempo: 120,
  },
  {
    codigo: '000032',
    descripcion: 'HISTEROSCOPIA QUIRURGICA',
    codigoEspecialidad: '005',
    tiempo: 90,
  },
  {
    codigo: '000033',
    descripcion: 'EXTRACCION DE DIU',
    codigoEspecialidad: '005',
    tiempo: 30,
  },
  {
    codigo: '000034',
    descripcion: 'LAPARATOMIA',
    codigoEspecialidad: '005',
    tiempo: 120,
  },
  {
    codigo: '000035',
    descripcion: 'LEGRADO BIOPSICO',
    codigoEspecialidad: '005',
    tiempo: 30,
  },
  {
    codigo: '000036',
    descripcion: 'BTB',
    codigoEspecialidad: '002',
    tiempo: 60,
  },
  {
    codigo: '000037',
    descripcion: 'EXTRIRPACION DE POLIPO CERVICAL',
    codigoEspecialidad: '005',
    tiempo: 60,
  },
  {
    codigo: '000038',
    descripcion: 'LAPARASCOPIA DIAGNOSTICA',
    codigoEspecialidad: '005',
    tiempo: 120,
  },
  {
    codigo: '000039',
    descripcion: 'RETIRO DE CERCLAJE',
    codigoEspecialidad: '005',
    tiempo: 60,
  },
  {
    codigo: '000040',
    descripcion: 'HISTEROSCOPIA DIAGNOSTICA',
    codigoEspecialidad: '005',
    tiempo: 90,
  },
  {
    codigo: '000041',
    descripcion: 'LIPOSUCCION',
    codigoEspecialidad: '005',
    tiempo: 210,
  },
  {
    codigo: '000024',
    descripcion: 'TOT',
    codigoEspecialidad: '005',
    tiempo: 120,
  },
  {
    codigo: '000042',
    descripcion: 'AUMENTO DE MAMA CON IMPLANTES',
    codigoEspecialidad: '005',
    tiempo: 120,
  },
  {
    codigo: '000043',
    descripcion: 'RINOPLASTIA',
    codigoEspecialidad: '005',
    tiempo: 120,
  },
  {
    codigo: '000044',
    descripcion: 'COLOCACION DVP',
    codigoEspecialidad: '005',
    tiempo: 120,
  },
  {
    codigo: '000045',
    descripcion: 'EXCERISIS DE FIBROADENOMA DE MAMA',
    codigoEspecialidad: '005',
    tiempo: 90,
  },
  {
    codigo: '000046',
    descripcion: 'BIOPSIA DE MAMA',
    codigoEspecialidad: '005',
    tiempo: 90,
  },
  {
    codigo: '000047',
    descripcion: 'EXTIRPACION DE CONDUCTO MAMARIO',
    codigoEspecialidad: '005',
    tiempo: 90,
  },
  {
    codigo: '000048',
    descripcion: 'EXTIRPACION DE TUMOR DE VAGINA',
    codigoEspecialidad: '005',
    tiempo: 60,
  },
  {
    codigo: '000049',
    descripcion: 'LABIOPLASTIA',
    codigoEspecialidad: '005',
    tiempo: 60,
  },
  {
    codigo: '000050',
    descripcion: 'FETOSCOPIA',
    codigoEspecialidad: '005',
    tiempo: 120,
  },
  {
    codigo: '000051',
    descripcion: 'MIOMECTOMIA VAGINAL',
    codigoEspecialidad: '005',
    tiempo: 30,
  },
  {
    codigo: '000052',
    descripcion: 'RESECCION DE TABIQUE VAGINAL',
    codigoEspecialidad: '005',
    tiempo: 30,
  },
  {
    codigo: '000053',
    descripcion: 'DISECCION GANGLIO CENTINELA',
    codigoEspecialidad: '005',
    tiempo: 120,
  },
  {
    codigo: '000054',
    descripcion: 'AMEU BIOPSICO',
    codigoEspecialidad: '005',
    tiempo: 30,
  },
  {
    codigo: '000055',
    descripcion: 'EXTRIPACION DE TUMOR DE MAMA',
    codigoEspecialidad: '005',
    tiempo: 90,
  },
  {
    codigo: '000056',
    descripcion: 'BIOPSIA VULVAR',
    codigoEspecialidad: '005',
    tiempo: 60,
  },
  {
    codigo: '000057',
    descripcion: 'RESECCION DE GRANULOMA DE FONDO DE SACO VAGINAL',
    codigoEspecialidad: '005',
    tiempo: 60,
  },
  {
    codigo: '000058',
    descripcion: 'CURA QUIRURGICA DE ONFALOCELE',
    codigoEspecialidad: '005',
    tiempo: 120,
  },
  {
    codigo: '000059',
    descripcion: 'CIRUGIA DE OJO',
    codigoEspecialidad: '012',
    tiempo: 60,
  },
  {
    codigo: '000060',
    descripcion: 'CIRUGIA DE OJO',
    codigoEspecialidad: '012',
    tiempo: 60,
  },
  {
    codigo: '000061',
    descripcion: 'SINEQUIA VULVOVAGINAL',
    codigoEspecialidad: '005',
    tiempo: 90,
  },
  {
    codigo: '000063',
    descripcion: 'CIERRE DE DUCTUS',
    codigoEspecialidad: '011',
    tiempo: 120,
  },
  {
    codigo: '000064',
    descripcion: 'POLIPECTOMIA ENDOCERVICAL',
    codigoEspecialidad: '005',
    tiempo: 30,
  },
  {
    codigo: '000065',
    descripcion: 'DILATACION DE CUELLO UTERINO',
    codigoEspecialidad: '005',
    tiempo: 60,
  },
  {
    codigo: '000066',
    descripcion: 'POLIPECTOMIA CERVICAL',
    codigoEspecialidad: '005',
    tiempo: 60,
  },
  {
    codigo: '000005',
    descripcion: 'LAPARATOMIA EXPLORATORIA (NEONATAL)',
    codigoEspecialidad: '001',
    tiempo: 180,
  },
  {
    codigo: '000067',
    descripcion: 'TUMORECTOMIA VULVAR',
    codigoEspecialidad: '005',
    tiempo: 60,
  },
  {
    codigo: '000068',
    descripcion: 'QUISTE VULVAR',
    codigoEspecialidad: '005',
    tiempo: 60,
  },
  {
    codigo: '000069',
    descripcion: 'HISTEROTOMIA',
    codigoEspecialidad: '005',
    tiempo: 90,
  },
];

export const especialidades = [
  { codigo: '003', descripcion: 'CARDIOLOGIA' },
  { codigo: '005', descripcion: 'GINECOLOGIA' },
  { codigo: '002', descripcion: 'ANESTESIOLOGIA' },
  { codigo: '012', descripcion: 'OFTALMOLOGIA' },
  { codigo: '011', descripcion: 'CIRUGIA GENERAL' },
  { codigo: '001', descripcion: 'PEDIATRIA' },
];

export const camas = [
  { codigo: '034', descripcionCorto: 'R-A ', descripcion: 'CAMA R-A' },
  { codigo: '036', descripcionCorto: 'R-C ', descripcion: 'CAMA R-C' },
  { codigo: '035', descripcionCorto: 'R-B ', descripcion: 'CAMA R-B' },
  { codigo: '037', descripcionCorto: 'R-D ', descripcion: 'CAMA R-D' },
];

export const data = [
  {
    historia: 137698,
    paciente: 'CESPEDES POMALIMA ANTONELLA LUAN',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 137707,
    paciente: 'SOTO RODRIGUEZ ANNELIESE ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 137711,
    paciente: 'TOLEDO SANTILLAN XIMENA ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 137715,
    paciente: 'GARCIA GUTIERREZ RN 1 ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 137720,
    paciente: 'CHACON PALACIOS LUCIANA ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 137727,
    paciente: 'MULLINGS GUZMAN RN 1 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 137733,
    paciente: 'SANTOS GUAYLUPO ANDREA VICTORIA',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 137745,
    paciente: 'IZARRA SANJINEZ MAURIZIO GABRIEL',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 137752,
    paciente: 'LEON TORRES DE MUÑOZ RN 1 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 137790,
    paciente: 'QUISPE CUBA RN 1 ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 137811,
    paciente: 'SILINGARDI ZAPATER RN 1 ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 137795,
    paciente: 'QUIROZ JARA NAYDELI ALAIA',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 137821,
    paciente: 'DIAZ BURGOS RN 1 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 137816,
    paciente: 'VIRTO MAYTA LORENA ALEXANDRA',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 137814,
    paciente: 'KHALED SIFUENTES TAREK ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 137803,
    paciente: 'NORIEGA CHAVEZ ARIANA EMILIA',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 137831,
    paciente: 'ALVA MARAVI RN 2 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 137845,
    paciente: 'ROJAS PONCE ZOE ANNET',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 137862,
    paciente: 'ARCE DE LAS CASAS RN 1 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 137876,
    paciente: 'JIMENEZ CHAVEZ RN 2 ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 137856,
    paciente: 'RIOS VARGAS RN 2 ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 137852,
    paciente: 'VALCARCEL CUMPA LUZ ANGELICA ANTONELLA',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 137861,
    paciente: 'FERNANDEZ RENDON BIANCA ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 137866,
    paciente: 'CUYA TANTAS SANTIAGO GONZALO',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 137904,
    paciente: 'ZAPATA CRUZ RN 1 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 137886,
    paciente: 'CHUQUIN VIDAL GONZALO ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 137896,
    paciente: 'BAUMANN DEGRACIA ALANNA MONTSERRAT',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 137931,
    paciente: 'ALMEIDA NUÑEZ RN 1 ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 137943,
    paciente: 'ESPINOZA CABRERA YANINA ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 137908,
    paciente: 'KONG MORENO MARIA PAZ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 137785,
    paciente: 'HURTADO URIBIA RN 1 ',
    sexo: 'M',
    edad: 0,
  },
  { historia: 137960, paciente: 'BAZAN ORE RN 1 ', sexo: 'M', edad: 0 },
  {
    historia: 137968,
    paciente: 'CABREDO CHANAVA JUAN PABLO',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 137941,
    paciente: 'ARNAO IZAGUIRRE CATALINA ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 137929,
    paciente: 'MISME LOZANO MAURIZIO ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 137978,
    paciente: 'HEREDIA FLORES RN 1 ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 137981,
    paciente: 'DE LA CRUZ TALLA DE DIAZ RN 1 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 137966,
    paciente: 'LEON ARISTONDO RN 1 ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 137986,
    paciente: 'ANGELES DIAZ RN 1 ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 137993,
    paciente: 'PICHARDO SIMON RN ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 137996,
    paciente: 'FLORES QUEZADA GAEL ADRIANO',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138001,
    paciente: 'PAZ ESPINOZA GIANNA ARLET',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138012,
    paciente: 'CAMPOS TRUJILLO RN 1 ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138032,
    paciente: 'VELASQUEZ BAUTISTA RN ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138051,
    paciente: 'JARAMILLO LLOCLLA RN 1 ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138057,
    paciente: 'RAMOS CARRANZA JULIO MANUEL',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138053,
    paciente: 'RIVERA RUIZ NICOLAS ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138063,
    paciente: 'BENITES QUILCA OCTAVIO NICOLAS',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138046,
    paciente: 'MARTINEZ MATOS GAEL ALEXANDER',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138041,
    paciente: 'ZUÑIGA SILVA MIA CAMILA',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138077,
    paciente: 'RIVERA NALVARTE RN 1 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138073,
    paciente: 'ARANA URIBE PIO DE JESUS',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138072,
    paciente: 'VASQUEZ STOCICH LJUBIJSKA VIELKA VIOLE',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138086,
    paciente: 'PLAZA MANCHEGO RN 1 ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138071,
    paciente: 'SANCHEZ QUIROZ RN 2 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138122,
    paciente: 'PORTOCARRERO HORNA RN ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 137870,
    paciente: 'CABALLERO NUÑEZ BRUNO LEO',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138103,
    paciente: 'CORREA NATIVIDAD EMILIA ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138114,
    paciente: 'VERGARA VALERIO GIA CATALINA',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138107,
    paciente: 'ORTIZ TAPIA ANA LUCIA',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138126,
    paciente: 'PALACIOS ASMAT DYLAN MATEO',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138148,
    paciente: 'SILVA BELLIDO FLAVIA JULIETTE',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138181,
    paciente: 'HERRAN LEDESMA IGNACIO ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138210,
    paciente: 'JARQUIN CACERES MIKAELA VALENTINA',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138207,
    paciente: 'SAN ROMAN DURAN RN 1 ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138195,
    paciente: 'BARBOZA VIZCONDE IGNACIO SALOMÓN',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138221,
    paciente: 'ORESTTES ALAYO LUCCA ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138197,
    paciente: 'TOYOSATO GAKIYA RN 2 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138196,
    paciente: 'TOYOSATO GAKIYA RN 1 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138226,
    paciente: 'CHIRINOS ARREDONDO RN 1 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138230,
    paciente: 'SALCEDO ZUÑIGA RN 2 ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138229,
    paciente: 'AGURTO AGUIRRE RN 1 ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138240,
    paciente: 'ORTIZ GARCIA RN 1 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138260,
    paciente: 'FLORES OSORIO ANDRE FABRIZIO',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138272,
    paciente: 'GONZALES DE LA CRUZ MICAELA ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138306,
    paciente: 'ESLAVA ARMAS RN 3 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138268,
    paciente: 'BAZAN BOGGIO ALAI MARIA',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138302,
    paciente: 'ARANIBAR YRIGOYEN ZAID TAREK',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138321,
    paciente: 'RODRIGUEZ BENAVENTE DE SUCRE RN 1 ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138329,
    paciente: 'GARCIA ROSELL MONTENEGRO CAETANO ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138310,
    paciente: 'AZNARAN SANTOS MIA DANETTE',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138299,
    paciente: 'PALOMINO HINOSTROZA RODRIGO ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138292,
    paciente: 'ANTON FIGUEROA DOMENICA LUCIA',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138358,
    paciente: 'PAZ Y MIÑO LAY RN 1 ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138359,
    paciente: 'VASQUEZ PINAZO MATHIAS ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138361,
    paciente: 'ALANIA GUERRA CAYETANA ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138315,
    paciente: 'CASTRO PEREZ JOSEPH JUAN',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138112,
    paciente: 'BELTRAN IGARZA JULIAN ANDRES',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138395,
    paciente: 'REYNAUD MUSANTE RN ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138397,
    paciente: 'SOTO PERALTA RN 1 ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138391,
    paciente: 'ARICA SUAREZ HECTOR ADRIANO',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138393,
    paciente: 'SANCHEZ BELTRAN MAURIO GAEL',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138394,
    paciente: 'CACERES MATELLINI LEONARDO AUGUSTO',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138384,
    paciente: 'BUENO YACHI RAFAELA ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138379,
    paciente: 'PAZ HURTADO RN 1 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138396,
    paciente: 'SLJIVANCANIN REYNAGA PAVLE ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138407,
    paciente: 'GONZALES ACOSTA OSCAR SANTIAGO',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 137854,
    paciente: 'SUAREZ DEL CASTILLO MICHELLE PAOLA ANTONEL',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138419,
    paciente: 'PACHECO NIÑO DE GUZMAN CAMILA AMAIA',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138416,
    paciente: 'LOYOLA QUISPE EMILIA GABRIELA',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138432,
    paciente: 'TUCTO SALINAS RN ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138437,
    paciente: 'TORRES OSORIO ALONDRA ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138442,
    paciente: 'SANVITI FRANIC RN 1 ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138300,
    paciente: 'ASENCIO MILLA RN 1 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138424,
    paciente: 'NORERO FAVARATO MATTIA ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138453,
    paciente: 'FIGUEROA DIAZ RN 2 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138472,
    paciente: 'BUSTAMANTE ESPINOZA RN 3 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138462,
    paciente: 'RUIZ CUYA LEON GAEL',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138464,
    paciente: 'SILVA ROCA RN 1 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138507,
    paciente: 'VERA CHOZO LUIS ALBERTO',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138498,
    paciente: 'YAURI CHAMORRO RN 1 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138503,
    paciente: 'RIOS CHOQUE RN 1 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138500,
    paciente: 'DAMIAN MUNDACA LUIS FERNANDO',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138480,
    paciente: 'MICHELENA ARAUCO EMILIA ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138506,
    paciente: 'GROSSO AGUILAR RN 1 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138501,
    paciente: 'PRADO SOLIS CAMILA LUHANA',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138509,
    paciente: 'ESPINOZA MARCHENA ELENA DEL CARMEN',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138526,
    paciente: 'CRUZ CIEZA ALESSIA ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138496,
    paciente: 'CALDERON CAMPOS ANAHI GISELLE',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138558,
    paciente: 'OVERCASH MEZA HARRY FRANCIS',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138559,
    paciente: 'MALAVER BARON RN ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138551,
    paciente: 'FLORES JUAREZ GABRIEL IGNACIO',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138537,
    paciente: 'OKUMURA ZAMBRANO LUCIANO IGNACIO',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138565,
    paciente: 'OCAÑA TELLEZ RAFAELLA ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138578,
    paciente: 'QUINTANA CORTEZ RN 1 ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138577,
    paciente: 'LLATAS MONTEZA ITZEL ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138561,
    paciente: 'BAUTISTA NUÑEZ IRZIO AUGUSTO',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138602,
    paciente: 'LUMBRERAS SOMMERKAMP RN 1 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138579,
    paciente: 'AYALA FLORES RN 1 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138597,
    paciente: 'FONSECA SILVA ARTHUR ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138592,
    paciente: 'CAMPOS GONZALES RN 1 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138574,
    paciente: 'SALCEDO RAMIREZ GASTON RN 1 ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138625,
    paciente: 'ARANCIBIA JESUS LUCAS ANTONIO',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138626,
    paciente: 'DELEDESMA LLANOS RN ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138604,
    paciente: 'REAL SALDIVAR CARLOS GUILLERMO',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138637,
    paciente: 'TORRES CHIRINOS RN ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138649,
    paciente: 'PACHERRES QUISPE JOAQUIN ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138647,
    paciente: 'GARCIA ZIEGLER RN 1 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138659,
    paciente: 'ARANDA LOAYZA RN ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138667,
    paciente: 'HISTORIA CLINICA GENERAL ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138645,
    paciente: 'CONDORI ALANGUIA JOAQUIN NICOLAS',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138657,
    paciente: 'DONGO MENDOZA CATALINA ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138700,
    paciente: 'RAMOS ROBLES RN 1 ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138726,
    paciente: 'QUEVEDO SANTILLAN RN 1 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138710,
    paciente: 'GONZALES CHAVEZ RN 1 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138721,
    paciente: 'HERNANDEZ MOREYRA ALESSANDRO DYLAN',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138724,
    paciente: 'GROSO BARTUREN ARIANA ROSA DEL CARMEN',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138713,
    paciente: 'CALVO AGUIRRE GIA CHRISTINE',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138730,
    paciente: 'PINTO LAU MARIANA BELEN',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138749,
    paciente: 'IBAÑEZ NOGUEIRA NICOLE ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138739,
    paciente: 'REYES GUERRA ERNESTO GABRIEL ALEJANDRO',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138743,
    paciente: 'SIU CORTEZ ALANNA NASHIRA',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138772,
    paciente: 'HUAMAN GALLEGOS LEANDRO ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138786,
    paciente: 'ALDAVES LEYVA ARIANA ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138788,
    paciente: 'MARCHENA RIOS RN ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138793,
    paciente: 'ZUAZO REYES RN 2 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138750,
    paciente: 'VIRTO MAYTA LORENA ALEXANDRA',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138757,
    paciente: 'SOTO HUAMAN VANIA SARA',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138805,
    paciente: 'MAYO GUZMAN MACARENA ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138763,
    paciente: 'SANTA CRUZ VILLENA AITANA MARIA',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138813,
    paciente: 'HORNA ZAMUDIO RN 1 ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138812,
    paciente: 'PALACIOS MANCO MATHIAS FRANCO',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138815,
    paciente: 'LAURO DELUCCHI RN 2 ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 137857,
    paciente: 'GONZALES JUAREZ ALMA SOFIA',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138824,
    paciente: 'RIPALDA ESPINOZA RN ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138800,
    paciente: 'GARCES ZEVALLOS CATALINA SOFIA',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138817,
    paciente: 'PAZ POZO EMMA CAYETANA',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138609,
    paciente: 'SALAZAR PETROVICH DOMENICO ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138504,
    paciente: 'BRAVO DE RUEDA DIAZ RENATA LUCIA',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138836,
    paciente: 'JOHNSON MAYCOCK FELIPE MIGUEL',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138838,
    paciente: 'FELIPE REYES CATALINA LOIS',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138828,
    paciente: 'TORRES TINCOSO SOFIA JOSEFINA',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 137865,
    paciente: 'ZAMUDIO SANCHEZ CAMILA THAIS',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138237,
    paciente: 'PUESCAS CAMPOS LIAM ALFONSO',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138852,
    paciente: 'TAMARA LOZANO IVANNA MIA',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138849,
    paciente: 'ZENTENO MAMANI AURELIO ANTONIO',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138853,
    paciente: 'PINTO TELLO FABIAN ERNESTO',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138863,
    paciente: 'ALVARADO SALAZAR RN 1 ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138876,
    paciente: 'PAREDES VILCHEZ RN ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138905,
    paciente: 'ESPINOLA FRANCHINI KOA ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138919,
    paciente: 'ARQUIÑIGO CHILQUILLO ARLINE MARIA',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138916,
    paciente: 'CUSTODIO QUISPE JOSE VASCO',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138886,
    paciente: 'HERNA PONCE IAN EDRIC',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138912,
    paciente: 'PARDO MUÑOZ EMILIA ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138917,
    paciente: 'VIGIL RAMOS EMILIA FERNANDA',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138898,
    paciente: 'GARCIA ROSELL HERRERA ANA PAULA',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138895,
    paciente: 'ALVARADO CASTRO ALONDRA MIA',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138944,
    paciente: 'CABALLERO BEDON RN 1 ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138831,
    paciente: 'SANCHEZ MENDOZA RN 1 ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138924,
    paciente: 'EGOAVIL BERROSPI HITOMI ANTONIETA',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138947,
    paciente: 'RODRIGUEZ MENDOZA RN 2 ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138957,
    paciente: 'LUJAN RIOS DANIEL ALESSANDRO',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138963,
    paciente: 'TRUJILLO RAMIREZ RN 1 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138955,
    paciente: 'DIBOS ISRAEL RN 2 ',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138954,
    paciente: 'SUQUILANDA DONAYRE DOMENICA ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138960,
    paciente: 'TEMPLE BIELI-BIANCHI ATENEA ',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138946,
    paciente: 'GALVEZ ARNAO SERGIO BENJAMIN',
    sexo: 'M',
    edad: 0,
  },
  {
    historia: 138953,
    paciente: 'MIÑAN ALVARADO ALESSIA IVANA',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138948,
    paciente: 'FABIAN JUSCAMAITA MIA STEPHANY',
    sexo: 'F',
    edad: 0,
  },
  {
    historia: 138952,
    paciente: 'ASTUDILLO MEZA LEONEL ALESSANDRO',
    sexo: 'M',
    edad: 0,
  },
];

export const medicos = [
  {
    codigo: '143',
    nombre: 'MATOS MORALES EDWIN EDRAIN',
    codigoEspecialidad: '005',
  },
  {
    codigo: '145',
    nombre: 'WONG CHONG FELIX LEONCIO',
    codigoEspecialidad: '005',
  },
  {
    codigo: '150',
    nombre: 'BARRENACHEA SALAS ROSA UMER',
    codigoEspecialidad: '005',
  },
  {
    codigo: '144',
    nombre: 'MATOS MORALES JAVIER HUMBERTO',
    codigoEspecialidad: '005',
  },
  {
    codigo: '009',
    nombre: 'GUTIERREZ RAMOS MIGUEL',
    codigoEspecialidad: '005',
  },
  { codigo: '078', nombre: 'BONILLA VARGAS SAUL', codigoEspecialidad: '005' },
  {
    codigo: '001',
    nombre: 'TANG PLOOG LUIS EDUARDO',
    codigoEspecialidad: '005',
  },
  {
    codigo: '011',
    nombre: 'VILLAVICENCIO VEGA MANUEL ADOLFO',
    codigoEspecialidad: '005',
  },
  { codigo: '018', nombre: 'CHANG WONG LUIS', codigoEspecialidad: '005' },
  {
    codigo: '003',
    nombre: 'ALBINAGORTA OLORTEGUI ROBERTO',
    codigoEspecialidad: '005',
  },
  { codigo: '079', nombre: 'LABORATORIO BLUFSTEIN', codigoEspecialidad: '014' },
  {
    codigo: '151',
    nombre: 'NOLI ESPINOLA STHEFANY YESENIA',
    codigoEspecialidad: '010',
  },
  {
    codigo: '149',
    nombre: 'CANAHUIRE HUALLPA RUBÉN',
    codigoEspecialidad: '010',
  },
  {
    codigo: '026',
    nombre: 'CAMPODONICO OLCESE LORENA',
    codigoEspecialidad: '005',
  },
  {
    codigo: '040',
    nombre: 'PUENTE ARNAO TIRAVANTI JAVIER ANDRES',
    codigoEspecialidad: '005',
  },
  {
    codigo: '152',
    nombre: 'ONOFRE APAZA MELISSA GLADYS',
    codigoEspecialidad: '001',
  },
  {
    codigo: '035',
    nombre: 'ROSPIGLIOSI LOPEZ MARIA LUZ',
    codigoEspecialidad: '001',
  },
  {
    codigo: '029',
    nombre: 'PANTOJA ROSALES LYNDON JAVIER',
    codigoEspecialidad: '001',
  },
  {
    codigo: '133',
    nombre: 'SILVA PACHECO JHOANNA PATRICIA',
    codigoEspecialidad: '005',
  },
  {
    codigo: '148',
    nombre: 'HUARAZ ZULOAGA RUBEN CHRISTIAN',
    codigoEspecialidad: '005',
  },
  {
    codigo: '034',
    nombre: 'BORDA LUQUE GERALDINE ESMILDA',
    codigoEspecialidad: '001',
  },
  {
    codigo: '025',
    nombre: 'CANCHAYA OSORIO LUIS OVIDIO',
    codigoEspecialidad: '003',
  },
  {
    codigo: '042',
    nombre: 'VIDAL ORE HENRY ZOZIMO',
    codigoEspecialidad: '005',
  },
  {
    codigo: '108',
    nombre: 'YRAZABAL CRISTOBAL DENNIS ADOLFO',
    codigoEspecialidad: '001',
  },
  {
    codigo: '041',
    nombre: 'DE MELO DA CAS GABRIELLE KELEN',
    codigoEspecialidad: '005',
  },
  {
    codigo: '087',
    nombre: 'BORDA MEDEROS LUIS AUGUSTO',
    codigoEspecialidad: '011',
  },
  {
    codigo: '012',
    nombre: 'SALVATIERRA ACHA EDUARDO',
    codigoEspecialidad: '005',
  },
  {
    codigo: '153',
    nombre: 'SÁNCHEZ GÓNGORA AMADEO',
    codigoEspecialidad: '005',
  },
  {
    codigo: '154',
    nombre: 'CALLAHUI ORTIZ IRMA TERESA',
    codigoEspecialidad: '005',
  },
  {
    codigo: '022',
    nombre: 'NAKAMURA HIDAKA ROBERTO',
    codigoEspecialidad: '001',
  },
  { codigo: '050', nombre: 'GALDOS KAJATT OSCAR', codigoEspecialidad: '005' },
  {
    codigo: '060',
    nombre: 'ROMAN ACUÑA CELIA APOLONIA',
    codigoEspecialidad: '002',
  },
  { codigo: '068', nombre: 'CHUNG JOO BEATRIZ', codigoEspecialidad: '005' },
  {
    codigo: '061',
    nombre: 'ESCUDERO DIAZ FRANCISCO RAFAEL',
    codigoEspecialidad: '005',
  },
  {
    codigo: '063',
    nombre: 'ZAPATA GARCIA JORGE GABRIEL',
    codigoEspecialidad: '005',
  },
  {
    codigo: '086',
    nombre: 'CANO MENDOZA CESAR AUGUSTO',
    codigoEspecialidad: '011',
  },
  {
    codigo: '089',
    nombre: 'VELARDE QUEVEDO JAIME RICARDO',
    codigoEspecialidad: '011',
  },
  { codigo: '057', nombre: 'POOL DE PEDIATRAS', codigoEspecialidad: '001' },
  {
    codigo: '117',
    nombre: 'LACUNZA PAREDES ROMMEL OMAR',
    codigoEspecialidad: '010',
  },
  {
    codigo: '131',
    nombre: 'BRITO HURTADO JULIO GUILLERMO',
    codigoEspecialidad: '005',
  },
  {
    codigo: '020',
    nombre: 'CHUECA OSTOLAZA ALBERTO',
    codigoEspecialidad: '001',
  },
  {
    codigo: '083',
    nombre: 'ESCUDERO CORNEJO CESAR',
    codigoEspecialidad: '012',
  },
  {
    codigo: '124',
    nombre: 'YAÑEZ IBARZENA PATRICIA',
    codigoEspecialidad: '001',
  },
  { codigo: '015', nombre: 'SILVA OLIVERA ARNALDO', codigoEspecialidad: '005' },
  {
    codigo: '170',
    nombre: 'AVALOS GÓMEZ JORGE ENRIQUE',
    codigoEspecialidad: '005',
  },
  {
    codigo: '104',
    nombre: 'ARANCIBIA FERREIRA ERIC',
    codigoEspecialidad: '005',
  },
  {
    codigo: '002',
    nombre: 'SANDOVAL JIMENEZ ERNESTO',
    codigoEspecialidad: '005',
  },
  {
    codigo: '105',
    nombre: 'ROJAS VALDIVIA OSCAR ALFREDO',
    codigoEspecialidad: '005',
  },
  {
    codigo: '028',
    nombre: 'BRAÑEZ JARAMILLO FERNANDO',
    codigoEspecialidad: '005',
  },
  {
    codigo: '116',
    nombre: 'ZAVALA NINAMANGO LUIS ALBERTO',
    codigoEspecialidad: '001',
  },
  {
    codigo: '164',
    nombre: 'RUELAS ROQUE RICARDO LEONARDO',
    codigoEspecialidad: '011',
  },
  {
    codigo: '159',
    nombre: 'PARI GALINDO LENA SOLEDAD',
    codigoEspecialidad: '010',
  },
  {
    codigo: '155',
    nombre: 'ALFARO HURTADO JOEL DAVID',
    codigoEspecialidad: '005',
  },
  {
    codigo: '156',
    nombre: 'RICALDE CASAVERDE ANA MARIA',
    codigoEspecialidad: '005',
  },
  {
    codigo: '157',
    nombre: 'TALLEDO COLAN RENZO ANTONIO',
    codigoEspecialidad: '005',
  },
  {
    codigo: '158',
    nombre: 'PUYCAN CACERES LILIANA TERESA',
    codigoEspecialidad: '005',
  },
  {
    codigo: '171',
    nombre: 'TERAN HUAMAN ALEXANDER ARMANDO',
    codigoEspecialidad: '001',
  },
  {
    codigo: '160',
    nombre: 'CARRIÓN JANAMPA VICTORIA ESTHER',
    codigoEspecialidad: '005',
  },
  {
    codigo: '097',
    nombre: 'TELLO PINTO ROXANA AMPARO',
    codigoEspecialidad: '001',
  },
  {
    codigo: '010',
    nombre: 'CARDENAS VILLACORTA GILBERTO',
    codigoEspecialidad: '001',
  },
  {
    codigo: '032',
    nombre: 'SUMALAVIA GONZALEZ DANIEL',
    codigoEspecialidad: '001',
  },
  {
    codigo: '129',
    nombre: 'CASTRO BUENO CECILIA ELIZABETH',
    codigoEspecialidad: '010',
  },
  {
    codigo: '172',
    nombre: 'TINCOPA ARQUÍÑEGO KATIA SUSANA',
    codigoEspecialidad: '001',
  },
  {
    codigo: '162',
    nombre: 'NIÑO DE GUZMAN LEON IVAN',
    codigoEspecialidad: '011',
  },
  {
    codigo: '107',
    nombre: 'PEREZ PINO MIGUEL ALEJANDRO',
    codigoEspecialidad: '001',
  },
  {
    codigo: '163',
    nombre: 'VARGAS PELAEZ FERNANDO',
    codigoEspecialidad: '011',
  },
  { codigo: '019', nombre: 'LOPEZ ZEA ANA MARIA', codigoEspecialidad: '005' },
  {
    codigo: '070',
    nombre: 'PRESTACIONES NO MEDICAS',
    codigoEspecialidad: '005',
  },
  {
    codigo: '166',
    nombre: 'CORNEJO ACEVEDO JOSE ANTONIO',
    codigoEspecialidad: '003',
  },
  {
    codigo: '121',
    nombre: 'MONTERO PACORA ROSSANA',
    codigoEspecialidad: '005',
  },
  {
    codigo: '138',
    nombre: 'HERRERA CRUZADO CARLOS ANTONIO',
    codigoEspecialidad: '005',
  },
  {
    codigo: '140',
    nombre: 'LIMAY RIOS OSCAR ANTONIO',
    codigoEspecialidad: '005',
  },
  {
    codigo: '037',
    nombre: 'ALBORNOZ LEON NICEFORO LUDWING',
    codigoEspecialidad: '005',
  },
  {
    codigo: '142',
    nombre: 'VALDERRAMA ESCOBAR LUIS ENRIQUE',
    codigoEspecialidad: '005',
  },
  { codigo: '141', nombre: 'NEOCARE', codigoEspecialidad: '016' },
  {
    codigo: '004',
    nombre: 'CARDENAS DE GALDOS ROXANA LUZ',
    codigoEspecialidad: '006',
  },
  {
    codigo: '006',
    nombre: 'MERE HERNANDEZ CARMEN JULIA',
    codigoEspecialidad: '005',
  },
  { codigo: '016', nombre: 'CORTEZ SOSA MARIELA', codigoEspecialidad: '005' },
  {
    codigo: '110',
    nombre: 'CARI CHOQUEHUANCA LUZ ELIANA',
    codigoEspecialidad: '001',
  },
  {
    codigo: '109',
    nombre: 'VARGAS DELGADO JESSICA LISET',
    codigoEspecialidad: '001',
  },
  {
    codigo: '118',
    nombre: 'PONCE DIAZ SALLY VANESSA',
    codigoEspecialidad: '001',
  },
  {
    codigo: '067',
    nombre: 'QUIROZ CERNA DORIS AMPARO',
    codigoEspecialidad: '012',
  },
  {
    codigo: '055',
    nombre: 'ORIHUELA CARRERA PATRICIA',
    codigoEspecialidad: '005',
  },
  { codigo: '082', nombre: 'NUÑEZ MELGAR ROSA', codigoEspecialidad: '015' },
  {
    codigo: '101',
    nombre: 'CHU JON LAY LIDIA MICAELA',
    codigoEspecialidad: '005',
  },
  {
    codigo: '137',
    nombre: 'ASCENZO BATTISTINI MARIO LEOPOLDO',
    codigoEspecialidad: '005',
  },
  {
    codigo: '099',
    nombre: 'CHIRINOS SAIRE JESSICA',
    codigoEspecialidad: '001',
  },
  {
    codigo: '007',
    nombre: 'SOTO ROMERO MARIA PATRICIA',
    codigoEspecialidad: '005',
  },
  {
    codigo: '103',
    nombre: 'MANRIQUE ESPINOZA NADYA',
    codigoEspecialidad: '005',
  },
  { codigo: '064', nombre: 'MOROCHO TOCCI ROSA', codigoEspecialidad: '002' },
  {
    codigo: '008',
    nombre: 'YUI PINEDA LORENA VICTORIA',
    codigoEspecialidad: '005',
  },
  { codigo: '014', nombre: 'YARA HOKAMA YSABEL', codigoEspecialidad: '005' },
  {
    codigo: '106',
    nombre: 'CHACON ARDILES GIULIANA',
    codigoEspecialidad: '005',
  },
  {
    codigo: '033',
    nombre: 'MORALES COZ PATRICIA DIANA',
    codigoEspecialidad: '001',
  },
  {
    codigo: '056',
    nombre: 'PORTUGAL ROJAS LUZ MARINA',
    codigoEspecialidad: '010',
  },
  { codigo: '049', nombre: 'RIVAS FRANCHINI DIANA', codigoEspecialidad: '008' },
  {
    codigo: '139',
    nombre: 'CAVERO GARAY ABELARDO HAMILL',
    codigoEspecialidad: '001',
  },
  {
    codigo: '053',
    nombre: 'ALVAREZ MURILLO CARLOS',
    codigoEspecialidad: '003',
  },
  {
    codigo: '054',
    nombre: 'ESPINOZA QUINTEROS IVAN',
    codigoEspecialidad: '009',
  },
  {
    codigo: '071',
    nombre: 'LA TORRE ORTIZ MARCO ANTONIO',
    codigoEspecialidad: '003',
  },
  {
    codigo: '059',
    nombre: 'VEGA MARIATEGUI NESTOR LUIS',
    codigoEspecialidad: '005',
  },
  { codigo: '073', nombre: 'BARRETO ESPINOZA LUIS', codigoEspecialidad: '013' },
  {
    codigo: '096',
    nombre: 'BLUFSTEIN BANCO DE SANGRE',
    codigoEspecialidad: '014',
  },
  {
    codigo: '090',
    nombre: 'CIUDAD REYNAUD MANUEL ANTONIO',
    codigoEspecialidad: '005',
  },
  {
    codigo: '091',
    nombre: 'ROSAS HURTADO ENRIQUE EDGAR',
    codigoEspecialidad: '005',
  },
  { codigo: '093', nombre: 'TORRES MIRANDA CESAR', codigoEspecialidad: '001' },
  { codigo: '094', nombre: 'ARIAS STELLA JAVIER', codigoEspecialidad: '008' },
  {
    codigo: '092',
    nombre: 'HERNANDEZ DIAZ ROGER ANTONIO',
    codigoEspecialidad: '015',
  },
  {
    codigo: '085',
    nombre: 'MEJIA TUPA MARCO ANTONIO',
    codigoEspecialidad: '009',
  },
  {
    codigo: '112',
    nombre: 'DANZ DEL POZO JAVIER EDUARDO',
    codigoEspecialidad: '005',
  },
  { codigo: '046', nombre: 'DIEZ CHANG GUILLERMO', codigoEspecialidad: '005' },
  {
    codigo: '051',
    nombre: 'ESCALANTE KANASHIRO GUILLERMO',
    codigoEspecialidad: '005',
  },
  { codigo: '081', nombre: 'PEREZ SOLF KARL YGOR', codigoEspecialidad: '005' },
  {
    codigo: '125',
    nombre: 'ACHO CARRANZA EDWIN AUGUSTO',
    codigoEspecialidad: '017',
  },
  {
    codigo: '039',
    nombre: 'CAMPODONICO OLCESE DAVID GIOVANNI',
    codigoEspecialidad: '005',
  },
  {
    codigo: '069',
    nombre: 'HERNANDEZ ALARCON RONALD',
    codigoEspecialidad: '005',
  },
  {
    codigo: '072',
    nombre: 'POOL DE GINECOLOGOS DE GUARDIA',
    codigoEspecialidad: '005',
  },
  {
    codigo: '074',
    nombre: 'FIGUEROA ZEVALLOS VICTOR EDUARDO',
    codigoEspecialidad: '005',
  },
  { codigo: '075', nombre: 'CHUMBES DIAZ OSCAR', codigoEspecialidad: '001' },
  { codigo: '077', nombre: 'FALCON RUIZ MAYER', codigoEspecialidad: '001' },
  {
    codigo: '119',
    nombre: 'RIVERA ALTAMIRANO PORFIRIO',
    codigoEspecialidad: '001',
  },
  { codigo: '132', nombre: 'DAZA ARIAS RAÚL BORIS', codigoEspecialidad: '001' },
  {
    codigo: '135',
    nombre: 'NAVARRO ACOSTA ALAN GIANCARLO',
    codigoEspecialidad: '001',
  },
  {
    codigo: '136',
    nombre: 'GIL GUEVARA ENRIQUE DAMIAN',
    codigoEspecialidad: '005',
  },
  {
    codigo: '044',
    nombre: 'DELGADO DELGADO JOSE ANTONIO',
    codigoEspecialidad: '005',
  },
  {
    codigo: '128',
    nombre: 'MARREROS GRADOS JESÚS ERNESTO',
    codigoEspecialidad: '005',
  },
  { codigo: '043', nombre: 'CAMARGO ROMAN ROXANA', codigoEspecialidad: '002' },
  {
    codigo: '062',
    nombre: 'OSORIO BASTIDAS SHIRLEY',
    codigoEspecialidad: '002',
  },
  {
    codigo: '047',
    nombre: 'GUERZONI CHAMBERGO ELENA',
    codigoEspecialidad: '002',
  },
  {
    codigo: '048',
    nombre: 'HUAMAN VEGA DOLORES OFELIA',
    codigoEspecialidad: '002',
  },
  {
    codigo: '147',
    nombre: 'HERMOZA PALZA FIORELLA GIOVANNA',
    codigoEspecialidad: '005',
  },
  {
    codigo: '100',
    nombre: 'OCAÑA MENDOZA LUIS ENRIQUE',
    codigoEspecialidad: '001',
  },
  {
    codigo: '088',
    nombre: 'MARQUEZ TORRENT ADRIANA',
    codigoEspecialidad: '005',
  },
  {
    codigo: '065',
    nombre: 'KONG WONG VERONIKA PAOLA',
    codigoEspecialidad: '005',
  },
  {
    codigo: '098',
    nombre: 'BARRERA BURGA CARMEN MARCELA',
    codigoEspecialidad: '001',
  },
  {
    codigo: '165',
    nombre: 'PRADO GÓMEZ TOMMY LEONEL',
    codigoEspecialidad: '001',
  },
  {
    codigo: '027',
    nombre: 'SAPAICO MARAVI JOSE LUIS',
    codigoEspecialidad: '001',
  },
  {
    codigo: '095',
    nombre: 'ABURTO PITOT FERNANDO FELIX',
    codigoEspecialidad: '001',
  },
  {
    codigo: '134',
    nombre: 'SALINAS RAMIREZ MARÍA ELENA',
    codigoEspecialidad: '001',
  },
  {
    codigo: '167',
    nombre: 'SALAS CASTILLO PATRICIA LILIANA',
    codigoEspecialidad: '001',
  },
  { codigo: '168', nombre: 'LOVON LOPEZ JORGE', codigoEspecialidad: '001' },
  {
    codigo: '161',
    nombre: 'SAMANEZ PÉREZ JOSÉ MANUEL',
    codigoEspecialidad: '001',
  },
  {
    codigo: '024',
    nombre: 'COQUIS FRISANCHO EDGARD JULIO',
    codigoEspecialidad: '001',
  },
  { codigo: '122', nombre: 'RIOS MARROQUIN TANIA', codigoEspecialidad: '001' },
  {
    codigo: '031',
    nombre: 'GARCIA ENCINAS GUSTAVO',
    codigoEspecialidad: '001',
  },
  {
    codigo: '030',
    nombre: 'CAMPOS TEJADA JOSE FERNANDO',
    codigoEspecialidad: '001',
  },
  { codigo: '021', nombre: 'GOMEZ LAMLLEN JORGE', codigoEspecialidad: '001' },
  {
    codigo: '130',
    nombre: 'CORTEZ ESCALANTE RICHARD PAUL',
    codigoEspecialidad: '001',
  },
  {
    codigo: '176',
    nombre: 'NAZARIO REDONDO CONNY ELIZABETH',
    codigoEspecialidad: '005',
  },
  {
    codigo: '036',
    nombre: 'BARRON LOPEZ AZUCENA ROSSY',
    codigoEspecialidad: '001',
  },
  {
    codigo: '177',
    nombre: 'VENTURA LAVERIANO WALTER RICARDO',
    codigoEspecialidad: '005',
  },
  {
    codigo: '052',
    nombre: 'CUBA DIAZ LILIANA MELCHORITA',
    codigoEspecialidad: '001',
  },
  {
    codigo: '127',
    nombre: 'ASMAT COELLO KARLA JOSEFINA',
    codigoEspecialidad: '001',
  },
  { codigo: '111', nombre: 'NUÑEZ MORA ELIANA', codigoEspecialidad: '001' },
  {
    codigo: '169',
    nombre: 'RAMIREZ MACEDO EDUARDO OCTAVIO',
    codigoEspecialidad: '001',
  },
  {
    codigo: '173',
    nombre: 'NAVARRO AMARO BLANCA EVARISTA',
    codigoEspecialidad: '007',
  },
  {
    codigo: '174',
    nombre: 'MUÑOZ BARBIERI RODRIGO',
    codigoEspecialidad: '005',
  },
  {
    codigo: '175',
    nombre: 'BERROCAL ANAYA WALDO HOMERO',
    codigoEspecialidad: '001',
  },
  {
    codigo: '066',
    nombre: 'ALMANDOZ RUIZ MARIA ANGELA',
    codigoEspecialidad: '010',
  },
  {
    codigo: '005',
    nombre: 'FIGUEROA RIVAS EDGARDO CESAR',
    codigoEspecialidad: '001',
  },
  {
    codigo: '017',
    nombre: 'JACINTO HERVIAS GINA BEATRIZ',
    codigoEspecialidad: '005',
  },
  {
    codigo: '126',
    nombre: 'LUDEÑA MUÑOZ JUAN RAFAEL',
    codigoEspecialidad: '018',
  },
  { codigo: '023', nombre: 'AYQUE ROSAS FERNANDO', codigoEspecialidad: '001' },
  {
    codigo: '115',
    nombre: 'HERNANDEZ CHUNGA BRANY ADEMIR',
    codigoEspecialidad: '005',
  },
  {
    codigo: '013',
    nombre: 'RAMOS BARRIENTOS VICENTE PAUL',
    codigoEspecialidad: '005',
  },
  {
    codigo: '178',
    nombre: 'TINCOPA ARQUIÑEGO LISSIE MARLENI',
    codigoEspecialidad: '001',
  },
];
